services:
  postgres:
    image: postgres:16
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_DB: agentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - agentnet

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - agentnet



  access-request-server:
    build:
      context: .
      dockerfile: AccessRequest/Dockerfile
    container_name: AccessRequestServer
    ports:
      - "8003:8003"
    networks:
      - agentnet
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: agentdb
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_HOST: postgres

  security-agent:
    build:  
      context: ./Security_agent
      dockerfile: Dockerfile
    container_name: security-agent
    ports:    
      - "8004:8004"
    networks:
      - agentnet
    depends_on:
      - postgres
      - ollama
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_DB: agentdb
      OLLAMA_HOST: http://lmstudio:1234
    env_file:
      - ./Security_agent/.env



networks:
  agentnet:

volumes:
  postgres_data:
  ollama-data:
