from typing import Protocol, Any, Iterable

class DatabaseInterface(Protocol):
    async def get(self, table: Any, id: int): ...
    async def find(self, table: Any, **filters): ...
    async def create(self, table: Any, **data): ...
    async def update(self, obj: Any, **data): ...
    async def delete(self, obj: Any): ...
